version: "3"
services:
  my-redis-1:
    container_name: my-redis-1
    hostname: my-redis-1
    image: "bitnami/redis"
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "5000:6379"

  my-redis-2:
    container_name: my-redis-2
    hostname: my-redis-2
    image: "bitnami/redis"
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=my-redis-1
      - ALLOW_EMPTY_PASSWORD=yes
    ports: 
      - "5001:6379"
    depends_on:
      - my-redis-1

  redis-sentinel-1:
    container_name: redis-sentinel-1
    hostname: redis-sentinel-1
    image: "bitnami/redis-sentinel"
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_MASTER_HOST=my-redis-1
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_QUORUM=2
    ports:
      - "26379:26379"
    depends_on:
      - my-redis-1
      - my-redis-2

  redis-sentinel-2:
    container_name: redis-sentinel-2
    hostname: redis-sentinel-2
    image: "bitnami/redis-sentinel"
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_MASTER_HOST=my-redis-1
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_QUORUM=2
    ports:
      - "26380:26379"
    depends_on:
      - my-redis-1
      - my-redis-2

  redis-sentinel-3:
    container_name: redis-sentinel-3
    hostname: redis-sentinel-3
    image: "bitnami/redis-sentinel"
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_MASTER_HOST=my-redis-1
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_QUORUM=2
    ports:
      - "26381:26379"
    depends_on:
      - my-redis-1
      - my-redis-2

